### ISSUE TITLE
CIS Command not found

### ISSUE THREAD

**Issue by ghost** [charlesfoster/covid-illumina-snakemake#1]
Hi Dr. Foster. I am new to compiling COVID FASTQ's from Illumina, and I found your pipeline, and I am hoping to use it.

After downloading the code and installing it (I think), when I went to execute the CIS, I got a Command Not Found. I am thinking I need to change the $PATH in my local installation, but I am not sure where to point the path. I've included a screenshot below this message.

Any thoughts, advice, directions, pointing out what I did wrong is very apprecite.

Thanks,

Brian Delavan

![image](https://user-images.githubusercontent.com/91744154/168117292-c8805b15-6f62-4e7c-9843-2834de1acc49.png)

**Comment by charlesfoster** [comment]
Hi Brian,

I have a feeling you might have missed one of the steps during installation. The steps in order are:

1. Clone the repository and `cd` into it
2. Create the conda environment: `conda env create -f environment.yml`
3. Activate the conda environment: `conda activate CIS`
4. Install the CIS pipeline as a 'site package' within the environment: `pip install .`

I think you missed step number 4. Can you try running that command and see if it fixes the installation?

Cheers,
Charles

**Comment by ghost** [comment]
Hi Dr. Foster. I’ll try it as soon as I can.

Thanks for the quick response. I appreciate it.

Brian

**Comment by ghost** [comment]
Yup…that fixed it..

***@***.***

Awesome snake by the way!

Do I close the issue or do you? I can’t recall.

**Comment by ghost** [comment]
Hi Dr. Foster.

New problem: When I try to run CIS <path/to/fastqs>, I get an error about the database. Any advice and/or thoughts?

P.S. THAT SNAKE IS SO COOL! I LOVE IT!

***@***.***

**Comment by charlesfoster** [comment]
Hi Brian,

Glad you like the snake art.

When you experience any problems, it's helpful to copy and paste the error into Github issues for debugging purposes. I'm guessing in this case that you haven't installed a kraken2 database, which is used for analysis of negative controls. You can download a kraken2 database of your choice from here: https://benlangmead.github.io/aws-indexes/k2, then unpack the directory. 

To point CIS to your newly downloaded database, use the `-b` /  `--kraken2_db` option of CIS, or set the `$KRAKEN2_DEFAULT_DB` environmental variable, e.g. `export KRAKEN2_DEFAULT_DB=/path/to/kraken2_database`.

Cheers,
Charles

**Comment by ghost** [comment]
Dr. Foster.

Thank you for the advice on GITHUB. I am still learning GITHUB, and I appreciate all the advice and comments.

I have CIS working now, thanks to you. I appreciate your help very, very much.

Thanks,

Brian

**Comment by ghost** [comment]
Excellent Communication!
